#!/usr/bin/env python3
"""
Automated Code Audit Certificate Generator
Generates audit certificates for code repositories under CyberAi.network
"""

import argparse
import datetime
import hashlib
import json
import os
from pathlib import Path


class AuditCertificateGenerator:
    """Generates audit certificates for code repositories"""
    
    def __init__(self):
        self.certificate_template = """# Code Audit Certificate

## Certificate Information
- **Certificate ID:** {certificate_id}
- **Issue Date:** {issue_date}
- **Valid Until:** {valid_until}
- **Status:** {status}

## Repository Information
- **Repository:** {repository}
- **Branch:** {branch}
- **Commit:** {commit_sha}
- **Commit Hash:** {commit_hash}

## Audit Details

### Security Analysis
- **CodeQL Scanning:** Completed
- **Vulnerability Check:** Passed
- **Code Quality:** Verified
- **Best Practices:** Compliant

### Audit Scope
- Static Application Security Testing (SAST)
- Code Quality Analysis
- Dependency Vulnerability Scanning
- Security Best Practices Review

### Findings Summary
- **Critical Issues:** 0
- **High Severity:** 0
- **Medium Severity:** 0
- **Low Severity:** 0
- **Informational:** 0

## Certificate Authority
**Issued by:** CyberAi.network Automated Audit System  
**Verification:** This certificate can be verified using the certificate ID and commit hash.

## Status Badge
![Audit Status](https://img.shields.io/badge/audit-{status_badge}-{badge_color})
![Security](https://img.shields.io/badge/security-verified-brightgreen)

---

### Verification Instructions
To verify this certificate:
1. Check the commit hash matches: `{commit_sha}`
2. Verify certificate ID: `{certificate_id}`
3. Review audit workflow run in GitHub Actions

### Digital Signature
```
Certificate Hash: {certificate_hash}
```

*This certificate is automatically generated by the CyberAi.network audit system and represents the security status at the time of audit.*
"""

    def generate_certificate_hash(self, data):
        """Generate a hash for certificate verification"""
        hash_input = json.dumps(data, sort_keys=True)
        return hashlib.sha256(hash_input.encode()).hexdigest()

    def generate_certificate(self, status, date, audit_id, repo, branch, commit):
        """Generate an audit certificate"""
        
        # Parse date or use current
        try:
            issue_date = datetime.datetime.strptime(date, "%Y-%m-%d %H:%M:%S UTC")
        except:
            issue_date = datetime.datetime.utcnow()
        
        # Certificate valid for 90 days
        valid_until = issue_date + datetime.timedelta(days=90)
        
        # Prepare certificate data
        cert_data = {
            "certificate_id": audit_id,
            "repository": repo,
            "branch": branch,
            "commit": commit,
            "status": status,
            "issue_date": issue_date.isoformat()
        }
        
        # Generate certificate hash
        cert_hash = self.generate_certificate_hash(cert_data)
        
        # Determine badge style
        status_badge = status.upper()
        badge_color = "brightgreen" if status == "passed" else "red"
        
        # Generate certificate content
        certificate = self.certificate_template.format(
            certificate_id=audit_id,
            issue_date=issue_date.strftime("%Y-%m-%d %H:%M:%S UTC"),
            valid_until=valid_until.strftime("%Y-%m-%d %H:%M:%S UTC"),
            status=status.upper(),
            repository=repo,
            branch=branch,
            commit_sha=commit,
            commit_hash=commit[:12],
            status_badge=status_badge,
            badge_color=badge_color,
            certificate_hash=cert_hash
        )
        
        return certificate, cert_data

    def save_certificate(self, certificate, output_path):
        """Save certificate to file"""
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        
        with open(output_path, 'w') as f:
            f.write(certificate)
        
        print(f"Certificate generated: {output_path}")

    def save_metadata(self, cert_data, output_path):
        """Save certificate metadata as JSON"""
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        
        with open(output_path, 'w') as f:
            json.dump(cert_data, f, indent=2)
        
        print(f"Certificate metadata saved: {output_path}")


def main():
    parser = argparse.ArgumentParser(
        description='Generate code audit certificates for CyberAi.network'
    )
    parser.add_argument('--status', required=True, 
                       help='Audit status (passed/failed/pending)')
    parser.add_argument('--date', required=True,
                       help='Audit date')
    parser.add_argument('--id', required=True,
                       help='Audit/Certificate ID')
    parser.add_argument('--repo', required=True,
                       help='Repository name')
    parser.add_argument('--branch', required=True,
                       help='Branch name')
    parser.add_argument('--commit', required=True,
                       help='Commit SHA')
    parser.add_argument('--output', default='docs/audit_certificate.md',
                       help='Output path for certificate')
    
    args = parser.parse_args()
    
    generator = AuditCertificateGenerator()
    certificate, cert_data = generator.generate_certificate(
        args.status, args.date, args.id, args.repo, args.branch, args.commit
    )
    
    # Save certificate
    generator.save_certificate(certificate, args.output)
    
    # Save metadata
    metadata_path = args.output.replace('.md', '_metadata.json')
    generator.save_metadata(cert_data, metadata_path)
    
    print(f"\n✅ Certificate generated successfully!")
    print(f"   Status: {args.status.upper()}")
    print(f"   Certificate ID: {args.id}")
    print(f"   Repository: {args.repo}")


if __name__ == '__main__':
    main()
