/**
 * Comment Formatter
 * Formats audit results as GitHub PR comments
 */

const logger = require('../logger');

/**
 * Format audit summary as a PR comment
 * @param {Object} summary - Audit summary
 * @param {boolean} passed - Whether the audit passed
 * @returns {string} Formatted comment
 */
function formatComment(summary, passed) {
  logger.debug('Formatting PR comment');
  
  let comment = '';
  
  // Header with status
  if (passed) {
    comment += '## ✅ Code Audit Passed\n\n';
  } else {
    comment += '## ❌ Code Audit Failed\n\n';
  }
  
  // Summary stats
  comment += '### Summary\n\n';
  comment += `- **Files analyzed:** ${summary.filesAnalyzed}\n`;
  comment += `- **Analyzers run:** ${summary.analyzersRun}\n`;
  comment += `- **Total issues:** ${summary.totalIssues}\n`;
  comment += `  - 🔴 Errors: ${summary.errors}\n`;
  comment += `  - 🟡 Warnings: ${summary.warnings}\n`;
  comment += `  - ℹ️ Info: ${summary.infos}\n\n`;
  
  // Issues by analyzer
  if (Object.keys(summary.issuesByAnalyzer).length > 0) {
    comment += '### Issues by Analyzer\n\n';
    comment += '| Analyzer | Errors | Warnings | Info | Total |\n';
    comment += '|----------|--------|----------|------|-------|\n';
    
    Object.entries(summary.issuesByAnalyzer).forEach(([analyzer, stats]) => {
      comment += `| ${analyzer} | ${stats.errors} | ${stats.warnings} | ${stats.infos} | ${stats.total} |\n`;
    });
    
    comment += '\n';
  }
  
  // Top issues
  if (summary.totalIssues > 0) {
    comment += '### Top Issues\n\n';
    
    const topIssues = getTopIssuesForComment(summary, 10);
    
    topIssues.forEach((issue, index) => {
      const severity = issue.severity || 'warning';
      const severityIcon = getSeverityIcon(severity);
      comment += `${index + 1}. ${severityIcon} **${severity.toUpperCase()}**: ${issue.message}\n`;
      comment += `   - **File:** \`${issue.file}:${issue.line}\`\n`;
      if (issue.rule) {
        comment += `   - **Rule:** \`${issue.rule}\`\n`;
      }
      comment += '\n';
    });
    
    if (summary.totalIssues > 10) {
      comment += `<details>\n<summary>... and ${summary.totalIssues - 10} more issues</summary>\n\n`;
      comment += 'Run the audit locally or check the full logs for all issues.\n';
      comment += '</details>\n\n';
    }
  }
  
  // Footer
  comment += '---\n\n';
  comment += '*🤖 This comment was generated by [CodeAudit.sh](https://github.com/SolanaRemix/code-audit)*\n';
  
  return comment;
}

/**
 * Get top issues for comment
 * @param {Object} summary - Audit summary
 * @param {number} limit - Maximum number of issues
 * @returns {Array} Top issues
 */
function getTopIssuesForComment(summary, limit) {
  const allIssues = [];
  
  // Add errors first
  allIssues.push(...summary.issuesBySeverity.error);
  // Then warnings
  allIssues.push(...summary.issuesBySeverity.warning);
  // Then info
  allIssues.push(...summary.issuesBySeverity.info);
  
  return allIssues.slice(0, limit);
}

/**
 * Get icon for severity level
 * @param {string} severity - Severity level
 * @returns {string} Icon emoji
 */
function getSeverityIcon(severity) {
  const icons = {
    error: '🔴',
    warning: '🟡',
    info: 'ℹ️'
  };
  
  return icons[(severity || 'warning').toLowerCase()] || '⚪';
}

/**
 * Format inline comment for a specific issue
 * @param {Object} issue - Issue object
 * @returns {string} Formatted inline comment
 */
function formatInlineComment(issue) {
  const severityIcon = getSeverityIcon(issue.severity);
  
  let comment = `${severityIcon} **${issue.severity.toUpperCase()}**: ${issue.message}\n\n`;
  
  if (issue.rule) {
    comment += `**Rule:** \`${issue.rule}\`\n\n`;
  }
  
  if (issue.suggestion) {
    comment += `**Suggestion:** ${issue.suggestion}\n\n`;
  }
  
  comment += '*— CodeAudit.sh*';
  
  return comment;
}

/**
 * Format issues grouped by file
 * @param {Object} summary - Audit summary
 * @returns {string} Formatted output
 */
function formatIssuesByFile(summary) {
  let output = '### Issues by File\n\n';
  
  const sortedFiles = Object.entries(summary.issuesByFile)
    .sort(([, a], [, b]) => (b.errors + b.warnings) - (a.errors + a.warnings));
  
  sortedFiles.forEach(([file, fileIssues]) => {
    output += `#### \`${file}\`\n\n`;
    output += `- Errors: ${fileIssues.errors}, Warnings: ${fileIssues.warnings}, Info: ${fileIssues.infos}\n\n`;
    
    fileIssues.issues.slice(0, 5).forEach(issue => {
      const severityIcon = getSeverityIcon(issue.severity);
      output += `- ${severityIcon} Line ${issue.line}: ${issue.message}\n`;
    });
    
    if (fileIssues.issues.length > 5) {
      output += `- ... and ${fileIssues.issues.length - 5} more issues\n`;
    }
    
    output += '\n';
  });
  
  return output;
}

module.exports = {
  formatComment,
  formatInlineComment,
  formatIssuesByFile,
  getSeverityIcon
};
